config_name: "eval_dataset_01"  # Configuration name

seed: 1

# A-matrix cache path, uses system temp directory if not specified
cache_dir: "./cache"

scan_set:
  array_id: 1
  x_range: [-5, 5]
  y_range: [-5, 5]
  z_scan: 5
  x_grid: 101
  y_grid: 101
  fs: 10000
  nfft: 1024
  c: 343

source_set:
  nos: [6, 7, 8]  # List
  # freq: [500, 1000, 2000, 4000]  # List
  freq: [500]
  minEnergy: 0.1
  min_source_distance: 2  # Minimum source separation distance # 0 to ignore source distance
  num_samples: 10000  # Number of samples

target_map_set:
  blur_level: 5
  blur: True

norm_range: [0, 1]
use_FB: True

noise_level: [0, 50]
